<?xml version="1.0" encoding="utf-8"?><Database Name="Scanner" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="ConnectionString" ConnectionString="Data Source=vissu;Initial Catalog=Scanner;Integrated Security=True" Provider="System.Data.SqlClient" />
  <Table Name="dbo.vw_LookUpvalue" Member="vw_LookUpvalues">
    <Type Name="vw_LookUpvalue">
      <Column Name="Description" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="EBTSValue" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FieldId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_TransactionType" Member="vw_TransactionTypes">
    <Type Name="vw_TransactionType">
      <Column Name="TransactionTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Identifier" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Fileds" Member="vw_Fileds">
    <Type Name="vw_Filed">
      <Column Name="FieldName" Type="System.String" DbType="VarChar(62)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="HasLookup" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FieldId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsRequiredByField" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaxSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MinSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Identifier" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsAutoGenerated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TotTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tlbTransaction_Detail" Member="tlbTransaction_Details">
    <Type Name="tlbTransaction_Detail">
      <Column Name="Transaction_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_TotTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_FieldID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_Value" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Transaction_BinaryValue" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="tlbTransaction_Master_tlbTransaction_Detail" Member="tlbTransaction_Master" ThisKey="Transaction_ID" OtherKey="Transaction_ID" Type="tlbTransaction_Master" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tlbTransaction_Master" Member="tlbTransaction_Masters">
    <Type Name="tlbTransaction_Master">
      <Column Name="Transaction_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Transaction_TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_Desc" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tlbTransaction_Master_tlbTransaction_Detail" Member="tlbTransaction_Details" ThisKey="Transaction_ID" OtherKey="Transaction_ID" Type="tlbTransaction_Detail" />
    </Type>
  </Table>
  <Table Name="dbo.vw_LogicalRecordType" Member="vw_LogicalRecordTypes">
    <Type Name="vw_LogicalRecordType">
      <Column Name="Description" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TypeNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Identifier" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TotTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_TranactionFileds" Member="vw_TranactionFileds">
    <Type Name="vw_TranactionFiled">
      <Column Name="Identifier" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FieldName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Transaction_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_TotTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FieldId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HasLookup" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAutoGenerated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="MaxSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MinSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FieldNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ValidationRegEx" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="HelpText" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IsRequiredByField" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_BinaryValue" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Transaction_Value" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>