#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScanner
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Scanner")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttlbTransaction_Master(tlbTransaction_Master instance);
    partial void UpdatetlbTransaction_Master(tlbTransaction_Master instance);
    partial void DeletetlbTransaction_Master(tlbTransaction_Master instance);
    #endregion
		
		public DBDataContext() : 
				base("Data Source=vissu;Initial Catalog=Scanner;Integrated Security=Tru" +
						"e", mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vw_LookUpvalue> vw_LookUpvalues
		{
			get
			{
				return this.GetTable<vw_LookUpvalue>();
			}
		}
		
		public System.Data.Linq.Table<vw_TransactionType> vw_TransactionTypes
		{
			get
			{
				return this.GetTable<vw_TransactionType>();
			}
		}
		
		public System.Data.Linq.Table<vw_Filed> vw_Fileds
		{
			get
			{
				return this.GetTable<vw_Filed>();
			}
		}
		
		public System.Data.Linq.Table<tlbTransaction_Detail> tlbTransaction_Details
		{
			get
			{
				return this.GetTable<tlbTransaction_Detail>();
			}
		}
		
		public System.Data.Linq.Table<tlbTransaction_Master> tlbTransaction_Masters
		{
			get
			{
				return this.GetTable<tlbTransaction_Master>();
			}
		}
		
		public System.Data.Linq.Table<vw_LogicalRecordType> vw_LogicalRecordTypes
		{
			get
			{
				return this.GetTable<vw_LogicalRecordType>();
			}
		}
		
		public System.Data.Linq.Table<vw_TranactionFiled> vw_TranactionFileds
		{
			get
			{
				return this.GetTable<vw_TranactionFiled>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_LookUpvalue")]
	public partial class vw_LookUpvalue
	{
		
		private string _Description;
		
		private string _EBTSValue;
		
		private int _FieldId;
		
		public vw_LookUpvalue()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EBTSValue", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EBTSValue
		{
			get
			{
				return this._EBTSValue;
			}
			set
			{
				if ((this._EBTSValue != value))
				{
					this._EBTSValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldId", DbType="Int NOT NULL")]
		public int FieldId
		{
			get
			{
				return this._FieldId;
			}
			set
			{
				if ((this._FieldId != value))
				{
					this._FieldId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_TransactionType")]
	public partial class vw_TransactionType
	{
		
		private int _TransactionTypeId;
		
		private string _Description;
		
		private string _Identifier;
		
		public vw_TransactionType()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionTypeId", DbType="Int NOT NULL")]
		public int TransactionTypeId
		{
			get
			{
				return this._TransactionTypeId;
			}
			set
			{
				if ((this._TransactionTypeId != value))
				{
					this._TransactionTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identifier", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Identifier
		{
			get
			{
				return this._Identifier;
			}
			set
			{
				if ((this._Identifier != value))
				{
					this._Identifier = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_Fileds")]
	public partial class vw_Filed
	{
		
		private string _FieldName;
		
		private string _Description;
		
		private bool _HasLookup;
		
		private int _FieldId;
		
		private bool _IsRequiredByField;
		
		private int _MaxSize;
		
		private int _MinSize;
		
		private string _Identifier;
		
		private int _DateTypeId;
		
		private int _TypeNumber;
		
		private bool _IsAutoGenerated;
		
		private int _TotTypeId;
		
		public vw_Filed()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldName", DbType="VarChar(62)")]
		public string FieldName
		{
			get
			{
				return this._FieldName;
			}
			set
			{
				if ((this._FieldName != value))
				{
					this._FieldName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasLookup", DbType="Bit NOT NULL")]
		public bool HasLookup
		{
			get
			{
				return this._HasLookup;
			}
			set
			{
				if ((this._HasLookup != value))
				{
					this._HasLookup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldId", DbType="Int NOT NULL")]
		public int FieldId
		{
			get
			{
				return this._FieldId;
			}
			set
			{
				if ((this._FieldId != value))
				{
					this._FieldId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRequiredByField", DbType="Bit NOT NULL")]
		public bool IsRequiredByField
		{
			get
			{
				return this._IsRequiredByField;
			}
			set
			{
				if ((this._IsRequiredByField != value))
				{
					this._IsRequiredByField = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxSize", DbType="Int NOT NULL")]
		public int MaxSize
		{
			get
			{
				return this._MaxSize;
			}
			set
			{
				if ((this._MaxSize != value))
				{
					this._MaxSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinSize", DbType="Int NOT NULL")]
		public int MinSize
		{
			get
			{
				return this._MinSize;
			}
			set
			{
				if ((this._MinSize != value))
				{
					this._MinSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identifier", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Identifier
		{
			get
			{
				return this._Identifier;
			}
			set
			{
				if ((this._Identifier != value))
				{
					this._Identifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTypeId", DbType="Int NOT NULL")]
		public int DateTypeId
		{
			get
			{
				return this._DateTypeId;
			}
			set
			{
				if ((this._DateTypeId != value))
				{
					this._DateTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeNumber", DbType="Int NOT NULL")]
		public int TypeNumber
		{
			get
			{
				return this._TypeNumber;
			}
			set
			{
				if ((this._TypeNumber != value))
				{
					this._TypeNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAutoGenerated", DbType="Bit NOT NULL")]
		public bool IsAutoGenerated
		{
			get
			{
				return this._IsAutoGenerated;
			}
			set
			{
				if ((this._IsAutoGenerated != value))
				{
					this._IsAutoGenerated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotTypeId", DbType="Int NOT NULL")]
		public int TotTypeId
		{
			get
			{
				return this._TotTypeId;
			}
			set
			{
				if ((this._TotTypeId != value))
				{
					this._TotTypeId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tlbTransaction_Detail")]
	public partial class tlbTransaction_Detail
	{
		
		private int _Transaction_ID;
		
		private int _Transaction_TotTypeId;
		
		private int _Transaction_FieldID;
		
		private string _Transaction_Value;
		
		private System.Data.Linq.Binary _Transaction_BinaryValue;

        private string _Transaction_DisplayFieldName;
       

        public tlbTransaction_Detail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_ID", DbType="Int NOT NULL")]
		public int Transaction_ID
		{
			get
			{
				return this._Transaction_ID;
			}
			set
			{
				if ((this._Transaction_ID != value))
				{
					this._Transaction_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_TotTypeId", DbType="Int NOT NULL")]
		public int Transaction_TotTypeId
		{
			get
			{
				return this._Transaction_TotTypeId;
			}
			set
			{
				if ((this._Transaction_TotTypeId != value))
				{
					this._Transaction_TotTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_FieldID", DbType="Int NOT NULL")]
		public int Transaction_FieldID
		{
			get
			{
				return this._Transaction_FieldID;
			}
			set
			{
				if ((this._Transaction_FieldID != value))
				{
					this._Transaction_FieldID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_Value", DbType="VarChar(50)")]
		public string Transaction_Value
		{
			get
			{
				return this._Transaction_Value;
			}
			set
			{
				if ((this._Transaction_Value != value))
				{
					this._Transaction_Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_BinaryValue", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Transaction_BinaryValue
		{
			get
			{
				return this._Transaction_BinaryValue;
			}
			set
			{
				if ((this._Transaction_BinaryValue != value))
				{
					this._Transaction_BinaryValue = value;
				}
			}
		}

        public string Transaction_DisplayFieldName
        {
            get
            {
                return this._Transaction_DisplayFieldName;
            }
            set
            {
                if ((this._Transaction_DisplayFieldName != value))
                {
                    this._Transaction_DisplayFieldName = value;
                }
            }
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tlbTransaction_Master")]
	public partial class tlbTransaction_Master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Transaction_ID;
		
		private int _Transaction_TypeId;
		
		private string _Transaction_Desc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTransaction_IDChanging(int value);
    partial void OnTransaction_IDChanged();
    partial void OnTransaction_TypeIdChanging(int value);
    partial void OnTransaction_TypeIdChanged();
    partial void OnTransaction_DescChanging(string value);
    partial void OnTransaction_DescChanged();
    #endregion
		
		public tlbTransaction_Master()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Transaction_ID
		{
			get
			{
				return this._Transaction_ID;
			}
			set
			{
				if ((this._Transaction_ID != value))
				{
					this.OnTransaction_IDChanging(value);
					this.SendPropertyChanging();
					this._Transaction_ID = value;
					this.SendPropertyChanged("Transaction_ID");
					this.OnTransaction_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_TypeId", DbType="Int NOT NULL")]
		public int Transaction_TypeId
		{
			get
			{
				return this._Transaction_TypeId;
			}
			set
			{
				if ((this._Transaction_TypeId != value))
				{
					this.OnTransaction_TypeIdChanging(value);
					this.SendPropertyChanging();
					this._Transaction_TypeId = value;
					this.SendPropertyChanged("Transaction_TypeId");
					this.OnTransaction_TypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_Desc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Transaction_Desc
		{
			get
			{
				return this._Transaction_Desc;
			}
			set
			{
				if ((this._Transaction_Desc != value))
				{
					this.OnTransaction_DescChanging(value);
					this.SendPropertyChanging();
					this._Transaction_Desc = value;
					this.SendPropertyChanged("Transaction_Desc");
					this.OnTransaction_DescChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_LogicalRecordType")]
	public partial class vw_LogicalRecordType
	{
		
		private string _Description;
		
		private int _TypeNumber;
		
		private string _Identifier;
		
		private int _TotTypeId;
		
		private int _TransactionTypeId;
		
		public vw_LogicalRecordType()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeNumber", DbType="Int NOT NULL")]
		public int TypeNumber
		{
			get
			{
				return this._TypeNumber;
			}
			set
			{
				if ((this._TypeNumber != value))
				{
					this._TypeNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identifier", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Identifier
		{
			get
			{
				return this._Identifier;
			}
			set
			{
				if ((this._Identifier != value))
				{
					this._Identifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotTypeId", DbType="Int NOT NULL")]
		public int TotTypeId
		{
			get
			{
				return this._TotTypeId;
			}
			set
			{
				if ((this._TotTypeId != value))
				{
					this._TotTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionTypeId", DbType="Int NOT NULL")]
		public int TransactionTypeId
		{
			get
			{
				return this._TransactionTypeId;
			}
			set
			{
				if ((this._TransactionTypeId != value))
				{
					this._TransactionTypeId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_TranactionFileds")]
	public partial class vw_TranactionFiled
	{
		
		private string _Identifier;
		
		private string _FieldName;
		
		private int _Transaction_ID;
		
		private int _Transaction_TotTypeId;
		
		private int _FieldId;
		
		private bool _HasLookup;
		
		private bool _IsAutoGenerated;
		
		private int _DateTypeId;
		
		private string _Description;
		
		private int _MaxSize;
		
		private int _MinSize;
		
		private int _FieldNumber;
		
		private string _ValidationRegEx;
		
		private string _HelpText;
		
		private bool _IsRequiredByField;
		
		private System.Data.Linq.Binary _Transaction_BinaryValue;
		
		private string _Transaction_Value;
		
		public vw_TranactionFiled()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identifier", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Identifier
		{
			get
			{
				return this._Identifier;
			}
			set
			{
				if ((this._Identifier != value))
				{
					this._Identifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldName", DbType="VarChar(150)")]
		public string FieldName
		{
			get
			{
				return this._FieldName;
			}
			set
			{
				if ((this._FieldName != value))
				{
					this._FieldName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_ID", DbType="Int NOT NULL")]
		public int Transaction_ID
		{
			get
			{
				return this._Transaction_ID;
			}
			set
			{
				if ((this._Transaction_ID != value))
				{
					this._Transaction_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_TotTypeId", DbType="Int NOT NULL")]
		public int Transaction_TotTypeId
		{
			get
			{
				return this._Transaction_TotTypeId;
			}
			set
			{
				if ((this._Transaction_TotTypeId != value))
				{
					this._Transaction_TotTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldId", DbType="Int NOT NULL")]
		public int FieldId
		{
			get
			{
				return this._FieldId;
			}
			set
			{
				if ((this._FieldId != value))
				{
					this._FieldId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasLookup", DbType="Bit NOT NULL")]
		public bool HasLookup
		{
			get
			{
				return this._HasLookup;
			}
			set
			{
				if ((this._HasLookup != value))
				{
					this._HasLookup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAutoGenerated", DbType="Bit NOT NULL")]
		public bool IsAutoGenerated
		{
			get
			{
				return this._IsAutoGenerated;
			}
			set
			{
				if ((this._IsAutoGenerated != value))
				{
					this._IsAutoGenerated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTypeId", DbType="Int NOT NULL")]
		public int DateTypeId
		{
			get
			{
				return this._DateTypeId;
			}
			set
			{
				if ((this._DateTypeId != value))
				{
					this._DateTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxSize", DbType="Int NOT NULL")]
		public int MaxSize
		{
			get
			{
				return this._MaxSize;
			}
			set
			{
				if ((this._MaxSize != value))
				{
					this._MaxSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinSize", DbType="Int NOT NULL")]
		public int MinSize
		{
			get
			{
				return this._MinSize;
			}
			set
			{
				if ((this._MinSize != value))
				{
					this._MinSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldNumber", DbType="Int NOT NULL")]
		public int FieldNumber
		{
			get
			{
				return this._FieldNumber;
			}
			set
			{
				if ((this._FieldNumber != value))
				{
					this._FieldNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidationRegEx", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string ValidationRegEx
		{
			get
			{
				return this._ValidationRegEx;
			}
			set
			{
				if ((this._ValidationRegEx != value))
				{
					this._ValidationRegEx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpText", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string HelpText
		{
			get
			{
				return this._HelpText;
			}
			set
			{
				if ((this._HelpText != value))
				{
					this._HelpText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRequiredByField", DbType="Bit NOT NULL")]
		public bool IsRequiredByField
		{
			get
			{
				return this._IsRequiredByField;
			}
			set
			{
				if ((this._IsRequiredByField != value))
				{
					this._IsRequiredByField = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_BinaryValue", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Transaction_BinaryValue
		{
			get
			{
				return this._Transaction_BinaryValue;
			}
			set
			{
				if ((this._Transaction_BinaryValue != value))
				{
					this._Transaction_BinaryValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_Value", DbType="VarChar(50)")]
		public string Transaction_Value
		{
			get
			{
				return this._Transaction_Value;
			}
			set
			{
				if ((this._Transaction_Value != value))
				{
					this._Transaction_Value = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
